zaeleus/noodles

noodles-sam/src/record.rs
noodles-sam/src/record/data.rs

Now that I've got the code from #15 working it really opened the floodgates 😁 
My next target: reading a BAM file, filtering by checking for a specific tag, and then writing a slightly modified BAM file with a new tag added. Specifically I'm checking for a barcode tag that's part of my selected set, and then adding a corrected barcode in a new tag and writing it to my new BAM file.
Unfortunately I got stuck on the last step. I could create a new `sam::Record` with the additional tag, but it felt clumsy to me--it didn't appear that there was a natural way to copy things, so I would need to use `Record::builder` and manually set all the fields (including checking for errors).
I thought maybe I could use the Rust structure-copying method of `Record{ data: new_data, ..old_record }` but all of …

Implementing DerefMut for sam::record::Data

---

noodles-bam/src/async/reader/builder.rs
noodles-bam/src/async/writer/builder.rs

I was excited to try out the new multi-threaded async functions, but I ran into what I think is a bug. If I try to build an AsyncWriter using the Builder and `set_worker_count`, it will fail to compile with
```
error[E0507]: cannot move out of a mutable reference
--> src/retag_bam.rs:54:22
|
54 |       let mut writer = bam::AsyncWriter::builder(file)
|  ______________________^
55 | |         .set_worker_count(8)
56 | |         .set_compression_level(Compression::fast())
| |___________________________________________________^ move occurs because value has type `bam::r#async::writer::builder::Builder<tokio::fs::File>`, which does not implement the `Copy` trait
error: aborting due to previous error
```
I believe this is because the builder methods were by reference, and they need to take …

builder methods should take ownership

---

noodles-bcf/src/lib.rs
noodles-vcf/src/lib.rs

I was playing around with some extensions to the `vcf`/`bcf` modules, and found that certain things are made difficult by the fact that some returned structs (`Records` and `Query` in `noodles-{vcf,bcf}`) are not exported, and hence cannot be referenced from outside `noodles`. I see that similar structs are exported in other parts of `noodles`, so I assume this is unintentional and made this small PR to fix.
For completeness sake, I started going through some of the other sub-crates to see if I could find other instances of the same pattern. I can find it in a few other places (e.g. `CompressionHeader`, `Container` in `noodles-cram`), but there I'm less sure if for some reason this is intentional, and, if not, what export structure you might prefer. Happy to help if you want to outsource …

Expose types in public interfaces

---

noodles-vcf/src/record/genotype/field/value/genotype.rs
noodles-vcf/src/record/genotype/field/value/genotype/allele.rs

Here were the basics discussed in #42. I was thinking the following might also be desirable:
1. Implement mutable getters for `position` and `phasing` for `Allele`.
2. Implement a public constructor for `Genotype`, as `pub fn new(alleles: Vec<Allele>) -> Self` and/or `From<Vec<Allele>> for Genotype`.
3. Implement `DerefMut<Target = [Allele]> for Genotype`.
However, I suppose these depend on how you envision `Genotype` being used in practice, so I thought you'd perhaps like to give some input on those before I forged ahead.

Access genotype alleles (Fixes #42)

---

noodles-bam/src/async/writer/record.rs
noodles-bam/src/reader/record/data/field/tag.rs
noodles-bam/src/writer/record.rs
noodles-sam/CHANGELOG.md
noodles-sam/src/record/data/field/tag.rs

By dropping the internal String from Tag::Other we gain performance, but
also the possibility to create `const` tags.
Closes #46

Change Tag::Other to [u8; LENGTH]

---

noodles-vcf/CHANGELOG.md
noodles-vcf/src/header.rs

Adds mutable getters for all structured fields of a VCF header. I also fixed a couple of typos in related, existing doc comments to make things match up.
Two points:
1. I didn't add doc tests for the new methods. I figured that they might make the doc pages unnecessarily long while being more or less self-explanatory together with the existing doc tests, but perhaps they'd still be good to have. Happy to back over and add these if you prefer? 
2. The header is still lacking mutable access to the unstructured fields. Perhaps it would make sense to add either `get_mut`/`delete` to go with `get`/`insert`, and/or simply add `records`/`records_mut` for full access? 
Closes #65

Add mutable access to VCF header

---

noodles-vcf/CHANGELOG.md
noodles-vcf/src/record.rs
noodles-vcf/src/record/alternate_bases.rs
noodles-vcf/src/record/genotypes.rs
noodles-vcf/src/record/genotypes/genotype.rs
noodles-vcf/src/record/genotypes/keys.rs
noodles-vcf/src/record/reference_bases.rs

I came across a situation where I needed to mutate the genotypes of existing VCF records. As in #65, I figured it'd be good to have `genotypes_mut`. In the process, it seemed natural to also implement `reference_bases_mut` and `alternate_bases_mut` as well as `DerefMut` for `ReferenceBases` and `AlternateBases` to also have mutable access to these parts of the record.
EDIT: Realised mutating the genotypes of an existing record required a bit more than I though. Implemented `DerefMut` for `Genotype` and `Keys` and a mutable getter for `Keys` also. As always, feel free to disregard or request changes as you see fit.

Add mutable access to VCF record

---

noodles-vcf/CHANGELOG.md
noodles-vcf/src/record/position.rs
noodles-vcf/src/record/quality_score.rs

Just a little ergonomic improvement, adding derives
- `PartialOrd`/`Ord` for `vcf::record::Position`
- `PartialOrd` for `vcf::record::QualityScore`
to avoid having to go in and out of the wrapped type for comparisons.

vcf/record: Derive PartialOrd/Ord for newtypes

---

noodles-gff/CHANGELOG.md
noodles-gff/examples/gff_view.rs
noodles-gff/examples/gff_write.rs
noodles-gff/src/line.rs
noodles-gff/src/writer.rs

I suggest we formalize `Comment` as its own type and add the related `write_comment` method to the writer. The argument for the former is one of type specificity being a net positive when available (since this is not really an unconstrained `String`, better to define the parameters within which a comment can exist). The argument for the second is simply that we do not have a method for adding comments to the writer. 
I have also updated the examples:
* `gff_view.rs` has been updated to print all content of the GFF file, not just the records. I have also changed it to use the `gff::Writer` pointed at stdout.
* `gff_write.rs` has been updated to demonstrate how to write a comment.

gff: Formalizes `Comment` and adds `write_comment` method to writer

---

noodles-gtf/CHANGELOG.md
noodles-gtf/src/line.rs
noodles-gtf/src/writer.rs

Adds a `write_line` method in the same manner as [`noodles/gtf`](https://github.com/zaeleus/noodles/commit/53b43c73e0b904778651bea02a5a529ff209688d).

gtf/writer: Adds `write_line` method to writer

---

noodles-bgzf/src/reader.rs

The index is sorted, we could do binary search ([`partition_point`](https://doc.rust-lang.org/core/primitive.slice.html#method.partition_point) method) on it.

bgzf/reader: Change linear search to binary search

---

noodles-bgzf/src/gzi.rs

Fixes #143. 
`strace` is recording 11 read operations now, rather than  9960 - which is more inline with `bgzip`.

bgzf/gzi/reader: wrap gzi Reader in a BufReader

---

noodles-bcf/src/reader.rs
noodles-util/CHANGELOG.md
noodles-util/Cargo.toml
noodles-util/examples/util_variant_view.rs
noodles-util/src/lib.rs
noodles-util/src/variant.rs
noodles-util/src/variant/format.rs
noodles-util/src/variant/reader.rs
noodles-util/src/variant/reader/builder.rs
noodles-vcf/src/lib.rs
noodles-vcf/src/reader.rs
noodles-vcf/src/variant_reader.rs

I needed something like the `noodles_util::alignment` module, but for the common variant call formats (corresponding to the various `--output-type` options  in `bcftools`). I was just playing around to see if this could be easily done in the same spirit as for the alignment module, which seems to be the case.
This PR contains the reader only. If you're happy to accept something like this, I can have a look at the corresponding writer in a follow-up PR (or here, if you prefer). Otherwise, feel free to close and I'll just pull out what I need for private use.

util: Variant reader

---

noodles-bcf/CHANGELOG.md
noodles-bcf/src/writer.rs
noodles-util/CHANGELOG.md
noodles-util/Cargo.toml
noodles-util/examples/util_variant_rewrite.rs
noodles-util/src/variant.rs
noodles-util/src/variant/writer.rs
noodles-util/src/variant/writer/builder.rs
noodles-vcf/CHANGELOG.md
noodles-vcf/src/lib.rs
noodles-vcf/src/variant_writer.rs
noodles-vcf/src/writer.rs

Closes #150 
The followup to #149, adding the `VariantWriter` trait in `noodles-vcf` and the `variant::Writer` in `noodles-util`.
As agreed in #150, I've left aside the issue of `StringMaps` in the impl for `VariantWriter` for now.
Mostly, this follows the implementation of `AlignmentWriter` and `alignment::Writer`, but I had to make a few choices about the compression behaviour for the BCF format that may warrant a bit of attention. Specifically,
- Specifying `None` for compression for BCF leads to a BGZF-compressed file using compression level 0.
- The default compression for BCF (and VCF) is `None`.
- The path extension `.bcf` leads to `None` for compression, unlike `.bcf.(gz|bgz)`.
As you mentioned in the previous PR, BCF should technically always be compressed, so I see how this …

util: Variant writer

---

noodles-bam/CHANGELOG.md
noodles-bam/src/record/codec/encoder/sequence.rs

[bam] makes sequence writer no-op for empty sequence.

---

noodles-refget/src/sequence/metadata.rs
noodles-refget/src/sequence/service.rs
noodles-refget/src/sequence/service/builder.rs

This PR addresses #185 and implements the minimal set of changes for updating the refget client to the current v2 refget specs.
The version number has been updated to `v0.2.0` to reflect the breaking changes.
The dependencies of the crate have also been updated - however, this is fully optional.
Any comments are welcome.

refget: Update to v2.0.0 specifications

---

noodles-vcf/src/async/reader.rs

Hi -- I noticed you recently added a lazy record for VCF reader. This has been nice in cases where I'm using the non-async reader. So, hoping to have a similar speed up in the async case, I'd like to add `read_lazy_record` to the async vcf reader. This is mostly a copy of the sync implementation, just w/ awaits and different trait bounds.
Thanks!

feat: add lazy record reader to vcf async reader

---

noodles-vcf/src/lazy/record/bounds.rs

Hi,
I think there's an issue with `info_range` for the lazy vcf record in that currently it's actually the range for `FILTERS`, so rather than being the info in the record, the filter info is duplicated.
So this PR updates that `info_range` method and adds tests that check the bounds defined in the object come out correctly via the methods.
Thanks,

fix: fix range for INFO for lazy vcf record bounds

---

noodles-vcf/CHANGELOG.md
noodles-vcf/src/async/reader.rs
noodles-vcf/src/reader.rs
noodles-vcf/src/reader/lazy_record.rs

Hi, using the lazy vcf reader, I think I found an issue w.r.t. how the fields are being parsed. In cases where not all fields are present, `read_field` will read into the next line causing `record.buf` to contain the record in question as it was parsed and the "raw" next record (because of the last `read_line` in `read_lazy_record`).
For example, if you modify test_read_lazy_record test to have two records, `&b"sq0\t1\t.\tA\t.\t.\tPASS\t.\nsq0\t1\t.\tA\t.\t.\tPASS\t."[..];`, the test fails because `record.buf` is actually `sq01.A..PASS.\nsq01\t.\tA\t.\t.\tPASS\t.` (the samples field has the next record).
```rust
#[tokio::test]
async fn test_read_lazy_record() -> io::Result<()> {
let mut src = &b"sq0\t1\t.\tA\t.\t.\tPASS\t.\nsq0\t1\t.\tA\t.\t.\tPASS\t."[..];
let mut record = …
```

fix: lazy vcf overreading into next record

---

noodles-util/CHANGELOG.md
noodles-util/Cargo.toml
noodles-util/examples/util_alignment_view_async.rs
noodles-util/src/alignment.rs
noodles-util/src/alignment/async.rs
noodles-util/src/alignment/async/io.rs
noodles-util/src/alignment/async/io/reader.rs
noodles-util/src/alignment/async/io/reader/builder.rs
noodles-util/src/lib.rs

See #286 for more details. 
Creating this as a draft so if I am too slow and you want to work on this sooner you can use where I got to (if you want).
Checklist

Add async alignment reader

---

Cargo.toml

More information here: https://trifectatech.org/blog/zlib-rs-is-faster-than-c/

Switch to more performant, 100% Rust zlib

---

noodles-refget/CHANGELOG.md
noodles-refget/src/lib.rs
noodles-refget/src/sequence/builder.rs
noodles-refget/src/sequence/metadata/builder.rs
noodles-refget/src/sequence/service/builder.rs

A proposed solution to handle non-successful status codes in the refget client (fixes #332).
- Throws an informative error with the non-successful response status code (these cases weren't directly handled before).
- Introduces the `Response` error, similar to the current htsget implementation.
- Slightly simplifies the error handling in the response.

Refget: Handle non-successful status codes

---

noodles-vcf/src/record/info.rs
noodles-vcf/src/record/info/field.rs

I have an indexed vcf file, and my program was spending ~half the time (according to a quick flamegraph) parsing the info fields looking for `END` while querying it.
This just skips the parsing of the fields we don't care about on `get`. `variant_end` goes from ~45% to ~14%[1] the flamegraph for my usecase, not the most accurate assessment, but the change seems straightforward enough.
Thank you for the great libraries!
[1] It's very noisy, but it settled around here after some more extreme initial numbers.

vcf/record/info: Avoid parsing skipped fields
